[general]
discord-invite = "fJBXvq28bx"
rules = [
    "No saying slurs.",
    "No spamming.",
    "No death threats / death wishes.",
    "No hacking.",
    "No mini knighting. (killing prisoners for the warden, as a prisoner)",
    "No bug abusing.",
    "No server lagging.",
    "No advertising."
]