[general]
discord-invite = "fJBXvq28bx"
rules = [
    "No saying slurs.",
    "No spamming.",
    "No death threats / death wishes.",
    "No hacking.",
    "No mini knighting. (killing prisoners for the warden, as a prisoner)",
    "No bug abusing.",
    "No server lagging.",
    "No advertising."
]

[warden.help]
help = { args = [""], description = "Shows you this menu." }
solitary = { args = ["name"], description = "Sends a player to solitary, later to torture them. <red>[PLAYER MUST BE DEAD]" }
target = { args = ["name"], description = "Turns a player in a target." }
prefix = { args = ["prefix"], description = "Adds a prefix to your name." }
fire = { args = ["guard name"], description = "Fires a guard from their job" }
resign = { args = [""], description = "Resigns you from your job." }
release = { args = ["name"], description = "Releases a player from solitary." }
pass = { args = ["name"], description = "Gives a player warden." }
guard = { args = ["name"], description = "Makes another player a guard." }
swat = { args = ["name"], description = "Makes another player a SWAT guard. <red>[REQUIRES 'SWAT GUARDS' UPGRADE!]" }
nurse = { args = ["name"], description = "Makes another player a nurse." }
intercom = { args = ["msg"], description = "Plays a loud message to all players." }
grammar = { args = [""], description = "Makes all guards type with proper grammar." }
mutechat = { args = [""], description = "Forces all players to use team chat." }
skip = { args = [""], description = "Skips roll call." }