name: PrisonGame
version: ${project.version}
main: prisongame.prisongame.PrisonGame
api-version: 1.19
commands:
  warden:
    description: Warden-Based commands.
    usage: /<command>
  resign:
    description: Resign from your current position/Rejoin from prisoner.
    usage: /<command>
  safereload:
    permission: litteraly.do.not.give.this.lmao
    description: Reloads the game
    usage: /<command>
  builder:
    permission: penis.mute
    description: build menu
    usage: /<command>
  nerdcheatcommand:
    permission: penis.cock
    description: gives 1000 dollahs
    usage: /<command>
  rstmoney:
    permission: penis.cock
    description: gives 0 dollahs
    usage: /<command> <player>
  amute:
    permission: penis.mute
    description: mute de playah
    usage: /<command> <player>
  pay:
    description: gib de monah
    usage: /<command> <player> <money>
  aunmute:
    permission: penis.unmute
    description: unmute de playah
    usage: /<command> <player>
  tc:
    aliases: teamchat
    description: Resign from your current position/Rejoin from prisoner.
    usage: /<command>
  bragrightpackage:
    permission: litteraly.do.not.give.this.lmao
    usage: /<command> <player>
  disc:
    aliases: discord
    description: Resign from your current position/Rejoin from prisoner.
    usage: /<command>
  accept:
    description: Accept a job.
    usage: /<command>
  hello:
    description: Hi!
    usage: /<command>