name: PrisonGame
version: ${project.version}
main: prisongame.prisongame.PrisonGame
api-version: 1.19
commands:
  warden:
    description: Warden-Based commands.
    usage: /<command>
  resign:
    description: Resign from your current position/Rejoin from prisoner.
    usage: /<command>
  nerdcheatcommand:
    permission: penis.cock
    description: gives 1000 dollahs
    usage: /<command>
  tc:
    aliases: teamchat
    description: Resign from your current position/Rejoin from prisoner.
    usage: /<command>
  disc:
    aliases: discord
    description: Resign from your current position/Rejoin from prisoner.
    usage: /<command>
  accept:
    description: Accept a job.
    usage: /<command>
  hello:
    description: Hi!
    usage: /<command>