name: Publish Release
on:
  push:
    branches:
      - develop
      - workflows
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Give permission for Gradle
      run: chmod +x ./gradlew
    - name: Run build with Gradle Wrapper
      run: ./gradlew reobfJar
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        title: ${{ env.GITHUB_SHA }}
        workdir: build/libs/
